### ISSUE TITLE
Extra argument to write ....._rmob.txt to chosen directory instead of the default directory 'logs'?

### ISSUE THREAD

**Issue by meteorkees** [rabssm/MeteorRadio#2]
The monthly_rmob.py file write the results back into the directory 'logs'. Is it possible to add a feature that with an extra argument the file ....._rmob.txt can be written to a chosen directory other then 'logs'?

Many thanks in advance!

Kees.

**Comment by rabssm** [comment]
Added -d command line option to specify output directory for RMOB files.
